<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFAThxhE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFAThxhE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFAThxhE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFAThxhE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFAThxhE\App_KernelDevDebugContainer([
    'container.build_hash' => 'FAThxhE',
    'container.build_id' => '07c187e6',
    'container.build_time' => 1651178644,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFAThxhE');
