<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX8TrMqT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX8TrMqT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX8TrMqT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX8TrMqT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX8TrMqT\App_KernelDevDebugContainer([
    'container.build_hash' => 'X8TrMqT',
    'container.build_id' => '99012e91',
    'container.build_time' => 1651156263,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX8TrMqT');
